# Example config file @ /usr/share/doc/mpv/mpv.conf

# Pretend to be a web browser. Might fix playback with some streaming sites,
# but also will break with shoutcast streams.
user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0"

# Subtitles
sub-auto=fuzzy

# fix A/V desync
pulse-latency-hacks=yes

# Enable playback cache
cache=yes
# Max cache = 15 minutes of video.
cache-secs=900
# cache-pause=no

#demuxer-max-bytes=2147483647
#demuxer-max-back-bytes=2147483647

# Use HW decoding for video.
vo=gpu
hwdec=auto-safe

# Resume where you left.
save-position-on-quit=yes
volume-max=150

# Prefer 1080p and no vp9 for youtube-dl.
ytdl-format="bestvideo[height<=?1080][vcodec!=vp9]+bestaudio/best"

#af=acompressor
#loop-file=inf

# Temporary fix for YT videos
ytdl=no
