#!/bin/sh
userresources="${XDG_CONFIG_HOME:="$HOME/.config"}"/X11/xresources
usermodmap="${XDG_CONFIG_HOME}"/X11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

# Set custom keyboard preferences.
if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Execute sxhkd at the beginning of the X startup script so that it grabs all the keys
# before these are grabbed by the built-in keybinder of the WM/DE.
sxhkd &

# Run some configuration commands
nice -n 19 xset s 120 300 &
nice -n 19 xsetroot -cursor_name left_ptr &

# Swap Caps-Lock with Escape for vim
# setxkbmap -option caps:swapescape

# Set Num Lock on.
# setleds -D +num

# Start some programs for graphical session.

# Run screen lock manager.
if command -v dim-screen.sh; then
    xss-lock -n dim-screen.sh -- /usr/local/bin/slock &
else
    xss-lock /usr/local/bin/slock &
fi

picom --experimental-backends &
nm-applet &
dunst &
# emacs --daemon &
lxsession &
unclutter --timeout 10 &

# setup environment for X session.
export MYTERM='st'

# start window manager
if [ "$TTY" = "/dev/tty2" ]; then
    export XDG_SESSION_DESKTOP='qtile'
    qtile start
elif [ "$TTY" = "/dev/tty1" ]; then
    export XDG_SESSION_DESKTOP='dwm'
    while type dwm > /dev/null; do dwm && continue || break; done
elif [ "$TTY" = "/dev/tty3" ]; then
    export XDG_SESSION_DESKTOP="xmonad"
    xmonad
fi

# instead of WM, start only 1 terminal in fullscreen
#alacritty
##alacritty -o window.position.x=20 -o window.position.y=20 -o window.dimensions.columns=800 -o window.dimensions.lines=600
#xterm -geometry 1300x700+5+5
