#!/bin/sh
userresources="${XDG_CONFIG_HOME:="$HOME/.config"}"/X11/xresources
usermodmap="${XDG_CONFIG_HOME}"/X11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

# Set custom keyboard preferences.
if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Execute sxhkd at the beginning of the X startup script so that it grabs all the keys
# before these are grabbed by the built-in keybinder of the WM/DE.
sxhkd &

# Swap Caps-Lock with Escape for vim
# setxkbmap -option caps:swapescape

# Set Num Lock on.
# setleds -D +num

# start some nice programs
xset s 180 300
xss-lock -n 'bash /usr/share/doc/xss-lock/dim-screen.sh' -- /usr/local/bin/slock &
picom --experimental-backends &
nm-applet &
xsetroot -cursor_name left_ptr &
dunst &
#emacs --daemon &
lxsession &
unclutter --timeout 10 &
libinput-gestures-setup start &

# start window manager
if [[ "$(tty)" == "/dev/tty1" ]]; then
    while type dwm > /dev/null; do dwm && continue || break; done
elif [[ "$(tty)" == "/dev/tty3" ]]; then
    xmonad
elif [[ "$(tty)" == "/dev/tty4" ]]; then
    qtile start
fi

# instead of WM, start only 1 terminal in fullscreen
#alacritty
##alacritty -o window.position.x=20 -o window.position.y=20 -o window.dimensions.columns=800 -o window.dimensions.lines=600
#xterm -geometry 1300x700+5+5
