font_size: 20
theme: pywal
tree_1:
  search:
    wiby: "https://www.wiby.me/"
    marginalia: "https://search.marginalia.nu/"
    sms:  "https://searchmysite.net/"
  program:
    github: "https://www.github.com/"
    leetcode: "https://www.leetcode.com/"
    neetcode: "https://www.neetcode.io/"
    aoc:
      - "https://www.adventofcode.com/"
      - "advent of code"
  people:
    gtlsgamr: "https://hitarththummar.xyz/"
    bugswriter: "https://bugswriter.com/"
    me: "https://hadouken.neocities.org/"
  tildes:
    ~varsh: "https://tildevarsh.in/"
    ~team: "https://tilde.team/"
    ~verse: "https://tildeverse.org/"

tree_2:
  docs:
    archwiki: "https://archlinux.org/"
    python:
      - "https://docs.python.org/"
      - "python docs"
    archive.org: "https://archive.org/"
  chill:
    xkcd: "https://xkcd.com/"
    chess: "https://chess.com/"
    odysee: "https://www.odysee.com/"
    memes:  "https://www.reddit.com/r/memes/"
    unixp0rn: "https://www.reddit.com/r/unixporn/"
  social:
    whatsapp: "https://web.whatsapp.com/"
    instagram: "https://instagram.com/"
    gmail: "https://mail.google.com/"
  tools:
    segfault: "https://projectsegfau.lt/"
    screensy: "https://screensy.marijn.it/#hadouken"
