[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#666666"
blue = "#81a2be"
cyan = "#54ced6"
green = "#9ec400"
magenta = "#b77ee0"
red = "#ff3334"
white = "#ebdbb2"
yellow = "#f0c674"

[colors.cursor]
cursor = "#773b41"
text = "#1d1f21"

[colors.normal]
black = "#1d1f21"
blue = "#81a2be"
cyan = "#70c0ba"
green = "#b5bd68"
magenta = "#b294bb"
red = "#cc6666"
white = "#373b41"
yellow = "#e6c547"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[colors.selection]
background = "#3e4451"
text = "CellForeground"

[cursor]
thickness = 0.25

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Bold"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mods = "Alt"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"
mods = "None"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "None"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[scrolling]
history = 5000
multiplier = 3

[shell]
args = ["-c", "zsh"]
program = "/usr/local/bin/utmp"

[window]
dynamic_padding = false
opacity = 0.95
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
