-------------------------------------------------
-- COLORSCHEMES
-------------------------------------------------

-- Uncomment just ONE of the following colorschemes!
-- local ok, _ = pcall(vim.cmd, 'colorscheme base16-dracula')
-- local ok, _ = pcall(vim.cmd, 'colorscheme base16-gruvbox-dark-medium')
-- local ok, _ = pcall(vim.cmd, 'colorscheme base16-monokai')
-- local ok, _ = pcall(vim.cmd, 'colorscheme base16-nord')
-- local ok, _ = pcall(vim.cmd, 'colorscheme base16-oceanicnext')
-- local ok, _ = pcall(vim.cmd, "colorscheme base16-onedark")
-- local ok, _ = pcall(vim.cmd, 'colorscheme palenight')
-- local ok, _ = pcall(vim.cmd, 'colorscheme base16-solarized-dark')
-- local ok, _ = pcall(vim.cmd, 'colorscheme base16-solarized-light')
-- local ok, _ = pcall(vim.cmd, 'colorscheme base16-tomorrow-night')
-- local ok, _ = pcall(vim.cmd, "colorscheme wal")

-- Highlight the region on yank
vim.api.nvim_create_autocmd("TextYankPost", {
	group = num_au,
	callback = function()
		vim.highlight.on_yank({ higroup = "Visual", timeout = 120 })
	end,
})

function ColorMyPencils()
    vim.cmd([[highlight Normal           ctermfg=15   ctermbg=none  cterm=none]])
    vim.cmd([[highlight LineNr           ctermfg=8    ctermbg=none  cterm=none]])
    vim.cmd([[highlight CursorLineNr     ctermfg=7    ctermbg=8     cterm=none]])
    vim.cmd([[highlight VertSplit        ctermfg=0    ctermbg=8     cterm=none]])
    vim.cmd([[highlight Statement        ctermfg=2    ctermbg=none  cterm=none]])
    vim.cmd([[highlight Directory        ctermfg=4    ctermbg=none  cterm=none]])
    vim.cmd([[highlight StatusLine       ctermfg=7    ctermbg=8     cterm=none]])
    vim.cmd([[highlight StatusLineNC     ctermfg=7    ctermbg=8     cterm=none]])
    vim.cmd([[highlight NERDTreeClosable ctermfg=2]])
    vim.cmd([[highlight NERDTreeOpenable ctermfg=8]])
    vim.cmd([[highlight Comment          ctermfg=4    ctermbg=none  cterm=italic]])
    vim.cmd([[highlight Constant         ctermfg=12   ctermbg=none  cterm=none]])
    vim.cmd([[highlight Special          ctermfg=4    ctermbg=none  cterm=none]])
    vim.cmd([[highlight Identifier       ctermfg=6    ctermbg=none  cterm=none]])
    vim.cmd([[highlight PreProc          ctermfg=5    ctermbg=none  cterm=none]])
    vim.cmd([[highlight String           ctermfg=12   ctermbg=none  cterm=none]])
    vim.cmd([[highlight Number           ctermfg=1    ctermbg=none  cterm=none]])
    vim.cmd([[highlight Function         ctermfg=1    ctermbg=none  cterm=none]])
    vim.cmd([[highlight Visual           ctermfg=1    ctermbg=none  cterm=none]])

    vim.cmd([[highlight WildMenu         ctermfg=0    ctermbg=80    cterm=none]])
    vim.cmd([[highlight Folded           ctermfg=103  ctermbg=234   cterm=none]])
    vim.cmd([[highlight FoldColumn       ctermfg=103  ctermbg=234   cterm=none]])
    vim.cmd([[highlight DiffAdd          ctermfg=none ctermbg=23    cterm=none]])
    vim.cmd([[highlight DiffChange       ctermfg=none ctermbg=56    cterm=none]])
    vim.cmd([[highlight DiffDelete       ctermfg=168  ctermbg=96    cterm=none]])
    vim.cmd([[highlight DiffText         ctermfg=0    ctermbg=80    cterm=none]])
    vim.cmd([[highlight SignColumn       ctermfg=244  ctermbg=235   cterm=none]])
    vim.cmd([[highlight Conceal          ctermfg=251  ctermbg=none  cterm=none]])
    vim.cmd([[highlight SpellBad         ctermfg=168  ctermbg=none  cterm=underline]])
    vim.cmd([[highlight SpellCap         ctermfg=80   ctermbg=none  cterm=underline]])
    vim.cmd([[highlight SpellRare        ctermfg=121  ctermbg=none  cterm=underline]])
    vim.cmd([[highlight SpellLocal       ctermfg=186  ctermbg=none  cterm=underline]])
    vim.cmd([[highlight Pmenu            ctermfg=251  ctermbg=234   cterm=none]])
    vim.cmd([[highlight PmenuSel         ctermfg=0    ctermbg=111   cterm=none]])
    vim.cmd([[highlight PmenuSbar        ctermfg=206  ctermbg=235   cterm=none]])
    vim.cmd([[highlight PmenuThumb       ctermfg=235  ctermbg=206   cterm=none]])
    vim.cmd([[highlight TabLine          ctermfg=244  ctermbg=234   cterm=none]])
    vim.cmd([[highlight TablineSel       ctermfg=0    ctermbg=247   cterm=none]])
    vim.cmd([[highlight TablineFill      ctermfg=244  ctermbg=234   cterm=none]])
    vim.cmd([[highlight CursorColumn     ctermfg=none ctermbg=236   cterm=none]])
    vim.cmd([[highlight CursorLine       ctermfg=none ctermbg=236   cterm=none]])
    vim.cmd([[highlight ColorColumn      ctermfg=none ctermbg=236   cterm=none]])
    vim.cmd([[highlight Cursor           ctermfg=0    ctermbg=5     cterm=none]])
    vim.cmd([[highlight htmlEndTag       ctermfg=114  ctermbg=none  cterm=none]])
    vim.cmd([[highlight xmlEndTag        ctermfg=114  ctermbg=none  cterm=none]])
end

ColorMyPencils()
